apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ble-rtls-data-pvc
  labels:
    app: ble-indoor-positioning
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
