apiVersion: v1
kind: Service
metadata:
  name: ble-location-engine-service
  labels:
    app: ble-indoor-positioning
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: ble-indoor-positioning
    component: location-engine
