idf_component_register(SRCS "main.cpp"
                            "BLEScanner.cpp"
                            "Observation.cpp"
                            "Statistics.cpp"
                            "Packet.cpp"
                            "config_manager.cpp"
                            "uart_handler.cpp"
                       INCLUDE_DIRS ".")
